services:
  biw-art-web:
    build: .
    container_name: biw_art_web
    restart: unless-stopped
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - biw_net

networks:
  biw_net:
    external: true
